import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { activitiesApi, type Activity, type Participation } from '@/api/activities'
import { AppButton } from '@/components/ui'
import { QueryState } from '@/components/shared/QueryState'
import { ParticipationPanel } from './ParticipationPanel'
import { formatDate } from '@/lib/utils'
export const origin = (p: Participation) => p.selection_source === 'student' ? 'Выбор ученика' : p.selection_source === 'staff' ? 'Добавлено командой' : 'Источник не указан'
export const progress = (p: Participation) => p.decision === 'suggested' ? 'Рекомендовано' : p.decision === 'not_interested' ? 'Не интересно' : ({not_started:'Планируем',in_progress:'В работе',submitted:'Заявка подана организатору',completed:'Завершено',cancelled:'Отменено'}[p.status])
const cell = 'px-4 py-4 align-top text-sm border-b border-ds-line'
export function CatalogTable({ search, direction, onOpen }: {search:string;direction:string;onOpen:(a:Activity)=>void}) {
  const q = useQuery({queryKey:['activities','catalog-rows'],queryFn:activitiesApi.catalogRows})
  const rows = (q.data ?? []).filter(({activity:a}) => (!direction || a.direction===direction) && `${a.title} ${a.organizer ?? ''} ${a.country ?? ''} ${a.kind ?? ''}`.toLowerCase().includes(search.toLowerCase()))
  return <QueryState isLoading={q.isLoading} isError={q.isError} error={q.error} onRetry={()=>q.refetch()}><div className="overflow-x-auto rounded-2xl border border-ds-line bg-ds-panel"><table className="w-full min-w-[1100px] text-left"><thead className="text-xs text-ds-muted"><tr>{['Активность / направление','Организатор / страна','Набор / сроки','Формат / стоимость','Условия / задание','Публикация',''].map((x,i)=><th key={i} className="px-4 py-3 font-semibold">{x}</th>)}</tr></thead><tbody>{rows.map(({activity:a,intake:i})=><tr key={`${a.id}-${i?.id}`} className="hover:bg-ds-bg"><td className={cell}><div className="font-bold">{a.title}</div><div className="mt-1 text-ds-muted">{[a.kind,a.direction].filter(Boolean).join(' · ')}</div></td><td className={cell}>{a.organizer || 'Уточняется'}<div className="mt-1 text-ds-muted">{a.country || 'Страна уточняется'}</div></td><td className={cell}>{i?.label || 'Нет наборов'}<div className="mt-1 max-w-xs text-ds-muted">{i?.deadline ? formatDate(i.deadline) : i?.dates_text || 'Сроки уточняются'}</div></td><td className={cell}>{i?.format || 'Формат уточняется'}<div className="mt-1 text-ds-muted">{i?.cost_state==='free'?'Бесплатно':i?.cost_state==='paid'?i.cost_text || 'Платно':'Стоимость уточняется'}</div></td><td className={cell}><p className="max-w-xs whitespace-pre-wrap">{a.eligibility || 'Требования уточняются'}</p><p className="mt-2 max-w-xs text-ds-muted">{a.assignment || 'Задание уточняется'}</p></td><td className={cell}>{a.publication==='published'?'Опубликовано':a.publication==='draft'?'Черновик':'Архив'}</td><td className={cell}><div className="flex flex-col gap-2"><AppButton disabled={a.publication==='archived'} onClick={()=>onOpen(a)}>Назначить</AppButton><AppButton variant="subtle" onClick={()=>onOpen(a)}>Подробнее</AppButton></div></td></tr>)}</tbody></table>{!rows.length && <p className="p-8 text-sm text-ds-muted">Активности не найдены. Измените фильтры или добавьте активность.</p>}</div></QueryState>
}
export function ParticipationsTable({ studentId }: {studentId?:string}) {
  const [search,setSearch]=useState(''); const [source,setSource]=useState(''); const [status,setStatus]=useState('');const [page,setPage]=useState(0);const [opened,setOpened]=useState<Participation|null>(null)
  const q=useQuery({queryKey:['activities','overview',studentId,search,source,status,page],queryFn:()=>activitiesApi.overview({...(studentId?{student_id:studentId}:{}),q:search,...(source?{source}:{}),...(status?{status}:{}),offset:page*25,limit:25})})
  return <div className="space-y-4">{opened && <ParticipationPanel item={opened} onClose={()=>setOpened(null)}/>}<div className="flex flex-wrap gap-3"><input aria-label="Поиск участий" className="min-w-64 flex-1 rounded-ctl border border-ds-line bg-ds-panel px-3 py-2 text-sm" placeholder="Ученик или активность" value={search} onChange={e=>{setSearch(e.target.value);setPage(0)}}/><select aria-label="Источник выбора" className="rounded-ctl border border-ds-line bg-ds-panel px-3 py-2 text-sm" value={source} onChange={e=>{setSource(e.target.value);setPage(0)}}><option value="">Все источники</option><option value="student">Выбор ученика</option><option value="staff">Добавлено командой</option><option value="unknown">Источник не указан</option></select><select aria-label="Статус участия" className="rounded-ctl border border-ds-line bg-ds-panel px-3 py-2 text-sm" value={status} onChange={e=>{setStatus(e.target.value);setPage(0)}}><option value="">Все статусы</option><option value="not_started">Планируем</option><option value="in_progress">В работе</option><option value="submitted">Заявка подана организатору</option><option value="completed">Завершено</option><option value="cancelled">Отменено</option></select></div><QueryState isLoading={q.isLoading} isError={q.isError} error={q.error} onRetry={()=>q.refetch()}><div className="overflow-x-auto rounded-2xl border border-ds-line bg-ds-panel"><table className="w-full min-w-[850px] text-left"><thead className="text-xs text-ds-muted"><tr>{['Ученик','Активность','Кто добавил','Состояние','Ментор',''].map(x=><th key={x} className="px-4 py-3">{x}</th>)}</tr></thead><tbody>{q.data?.items.map(p=><tr key={p.id} className="hover:bg-ds-bg"><td className={cell}>{p.student_name}</td><td className={cell}><div className="font-bold">{p.activity.title}</div><div className="mt-1 text-ds-muted">{p.intake.label}</div></td><td className={cell}>{origin(p)}</td><td className={cell}>{progress(p)}</td><td className={cell}>{p.mentor_name || 'Не назначен'}</td><td className={cell}><AppButton variant="subtle" onClick={()=>setOpened(p)}>План и задачи</AppButton></td></tr>)}</tbody></table>{!q.data?.items.length && <p className="p-8 text-sm text-ds-muted">Участий пока нет. Откройте каталог и назначьте активность ученику.</p>}</div><div className="flex items-center justify-between text-sm text-ds-muted"><span>Всего участий: {q.data?.total ?? 0}</span><div className="flex items-center gap-3"><AppButton variant="subtle" disabled={!page} onClick={()=>setPage(p=>p-1)}>Назад</AppButton><span>{page+1}</span><AppButton variant="subtle" disabled={(page+1)*25 >= (q.data?.total??0)} onClick={()=>setPage(p=>p+1)}>Далее</AppButton></div></div></QueryState></div>
}
