from fastapi import APIRouter

from app.api.v1.endpoints import (
    auth,
    audit,
    users,
    students,
    student_access,
    invites,
    contracts,
    contract_addenda,
    applications,
    services,
    guardians,
    payments,
    permissions,
    responsibilities,
    documents,
    portfolio,
    confidential_notes,
    tasks,
    checkins,
    countries,
    mentor_assignments,
    status_history,
    communication,
    notes,
    note_sessions,
    integrations,
    export,
    telegram_webhook,
    telegram_chats,
    sync,
    notion,
    roadmaps,
    questionnaires,
    meetings,
    universities,
    scholarships,
    knowledge,
    chat,
    portal,
    workspace,
    public,
    notifications,
    agreements,
    complaints,
    emergency_contacts,
    refund_cases,
    mzk_quality,
    mentor_rewards,
    reward_rules,
    credentials,
    student_universities,
    security_incidents,
    access_requests,
)

api_router = APIRouter(prefix="/api/v1")

api_router.include_router(auth.router)
api_router.include_router(audit.router)
api_router.include_router(users.router)
api_router.include_router(access_requests.router)
api_router.include_router(students.router)
api_router.include_router(student_access.router)
api_router.include_router(invites.router)
api_router.include_router(contracts.router)
api_router.include_router(contract_addenda.router)
api_router.include_router(applications.router)
api_router.include_router(services.router)
api_router.include_router(guardians.router)
api_router.include_router(payments.router)
api_router.include_router(permissions.router)
api_router.include_router(responsibilities.router)
api_router.include_router(documents.router)
api_router.include_router(portfolio.router)
api_router.include_router(confidential_notes.router)
api_router.include_router(tasks.router)
api_router.include_router(checkins.router)
api_router.include_router(countries.router)
api_router.include_router(mentor_assignments.router)
api_router.include_router(status_history.router)
api_router.include_router(communication.router)
api_router.include_router(notes.router)
api_router.include_router(note_sessions.router)
api_router.include_router(integrations.router)
api_router.include_router(export.router)
api_router.include_router(telegram_webhook.router)
api_router.include_router(telegram_chats.router)
api_router.include_router(sync.router)
api_router.include_router(notion.router)
api_router.include_router(roadmaps.router)
api_router.include_router(questionnaires.router)
api_router.include_router(meetings.router)
api_router.include_router(universities.router)
api_router.include_router(scholarships.router)
api_router.include_router(knowledge.router)
api_router.include_router(chat.router)
api_router.include_router(notifications.router)
api_router.include_router(portal.router)
api_router.include_router(workspace.router)
api_router.include_router(public.router)
api_router.include_router(agreements.router)
api_router.include_router(complaints.router)
api_router.include_router(emergency_contacts.router)
api_router.include_router(refund_cases.router)
api_router.include_router(mzk_quality.router)
api_router.include_router(mentor_rewards.router)
api_router.include_router(security_incidents.router)
api_router.include_router(reward_rules.router)
# credentials was written but never registered — its endpoints were unreachable.
api_router.include_router(credentials.router)
api_router.include_router(student_universities.router)
