import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { MemoryRouter } from 'react-router-dom'
import { afterEach, beforeEach, expect, it, vi } from 'vitest'
import StatusInboxPage from './StatusInboxPage'
const mocks=vi.hoisted(()=>({list:vi.fn(),notes:vi.fn(),review:vi.fn(),noteReview:vi.fn(),assign:vi.fn()}))
vi.mock('@/api',()=>({pendingInsightsApi:{listAll:mocks.list,review:mocks.review},notesApi:{list:mocks.notes,review:mocks.noteReview},mentorAssignmentsApi:{assignSelf:mocks.assign}}))
vi.mock('@/contexts/AuthContext',()=>({useAuth:()=>({user:{id:'mentor1'}})}))
vi.mock('@/hooks/use-toast',()=>({toast:vi.fn()}))
const proposal=(index:number,mine=true)=>({id:`p${index}`,student_id:`s${index}`,student_name:`Ученик ${index}`,is_mine:mine,insight_type:index%2?'call_summary':'status_update',confidence:index===0?.7:.95,status:'pending',risk_level:'low',created_at:`2026-10-03T${String(20-index%20).padStart(2,'0')}:00:00Z`,diff:[{field:'city',old_value:'Алматы',new_value:'Астана'}],unmatched_fields:{},responsibles:[],source_excerpt:'Подтверждаем направление обучения и выбор города. '.repeat(5),source_sender:'Ученик'})
function open(){render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false},mutations:{retry:false}}})}><MemoryRouter initialEntries={['/workspace/status']}><StatusInboxPage/></MemoryRouter></QueryClientProvider>)}
beforeEach(()=>{sessionStorage.clear();vi.clearAllMocks();mocks.list.mockImplementation(async(status:string)=>status==='pending'?[proposal(0),proposal(1,false)]:[]);mocks.notes.mockResolvedValue([]);mocks.review.mockResolvedValue({})})
afterEach(cleanup)
it('по умолчанию Мои, низкая уверенность выделена, Все сохраняется на сессию',async()=>{open();expect(await screen.findByText('Ученик 0')).toBeTruthy();expect(screen.queryByText('Ученик 1')).toBeNull();expect(screen.getByText('Проверьте · 70%')).toBeTruthy();fireEvent.click(screen.getByRole('tab',{name:/^Все$/}));expect(await screen.findByText('Ученик 1')).toBeTruthy();cleanup();open();expect(await screen.findByText('Ученик 1')).toBeTruthy()})
it('пустое Мои предлагает Все с фактическим счётчиком',async()=>{mocks.list.mockImplementation(async(status:string)=>status==='pending'?[proposal(1,false)]:[]);open();expect(await screen.findByText('Всё разобрано')).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:'Показать все (1)'}));expect(await screen.findByText('Ученик 1')).toBeTruthy()})
it('рендерит 20 групп и раскрывает только первые 5',async()=>{mocks.list.mockImplementation(async(status:string)=>status==='pending'?Array.from({length:24},(_,i)=>proposal(i)):[]);open();await screen.findByText('Ученик 0');expect(screen.getAllByRole('button',{name:/группу Ученик/})).toHaveLength(20);expect(screen.getAllByRole('button',{name:/Свернуть группу/})).toHaveLength(5);fireEvent.click(screen.getByRole('button',{name:'Показать ещё (4)'}));expect(screen.getAllByRole('button',{name:/группу Ученик/})).toHaveLength(24)})
it('подтверждение вызывает существующий API и убирает обработанное предложение',async()=>{open();await screen.findByText('Ученик 0');fireEvent.click(screen.getByRole('button',{name:/^Подтвердить$/}));await waitFor(()=>expect(mocks.review).toHaveBeenCalledWith('p0','approve'));expect(await screen.findByText('Всё разобрано')).toBeTruthy();expect(screen.queryByRole('button',{name:'Изменить'})).toBeNull()})
it('длинная ссылка показана чипом, имя студента ведёт в кабинет',async()=>{const i=proposal(0);i.diff=[{field:'transcript_resume_url',old_value:'',new_value:'https://docs.google.com/document/d/'+ 'long'.repeat(70)+'/edit'}];mocks.list.mockImplementation(async(status:string)=>status==='pending'?[i]:[]);open();const link=await screen.findByRole('link',{name:'Google Doc ↗'});expect(link.getAttribute('href')).toContain('longlong');expect(screen.getByRole('link',{name:'Ученик 0'})).toHaveAttribute('href','/workspace/students/s0');expect(screen.getByText('новое')).toBeTruthy()})
it('ошибка черновиков не маскируется пустым состоянием',async()=>{mocks.notes.mockRejectedValue(new Error('Нет связи'));open();fireEvent.click(screen.getByRole('tab',{name:'Черновики конспектов'}));expect(await screen.findByRole('alert')).toBeTruthy();expect(screen.queryByText('Всё разобрано')).toBeNull()})
